name: Build Desktop Apps

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
          
      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop
        
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build Windows app
        run: flutter build windows --release
        
      - name: Create Windows installer
        run: |
          mkdir windows-release
          cp -r build/windows/x64/runner/Release/* windows-release/
          
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: windows-release/

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
          
      - name: Enable macOS desktop
        run: flutter config --enable-macos-desktop
        
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build macOS app
        run: flutter build macos --release
        
      - name: Debug build output
        run: |
          echo "=== 检查构建输出 ==="
          echo "构建目录结构:"
          find build -type d 2>/dev/null | head -10 || echo "build 目录不存在"
          echo "查找 .app 文件:"
          find build -name "*.app" -type d 2>/dev/null || echo "未找到 .app 文件"
          
      - name: Create DMG
        run: |
          echo "=== 创建 DMG 文件 ==="
          
          # 查找 .app 文件
          APP_PATH=$(find build -name "*.app" -type d | head -1)
          
          if [ -n "$APP_PATH" ] && [ -d "$APP_PATH" ]; then
            echo "找到 app 文件: $APP_PATH"
            
            # 创建 DMG（使用英文名称）
            hdiutil create -volname "PasswordManager" -srcfolder "$APP_PATH" -ov -format UDZO "PasswordManager-macOS.dmg"
            
            if [ -f "PasswordManager-macOS.dmg" ]; then
              echo "DMG 文件创建成功!"
              ls -la PasswordManager-macOS.dmg
            else
              echo "DMG 文件创建失败!"
              exit 1
            fi
          else
            echo "错误: 未找到 .app 文件"
            echo "详细目录结构:"
            find build -type f | head -20
            exit 1
          fi
          
      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: PasswordManager-macOS.dmg 